### ISSUE TITLE
[pod-gateway]: The container will not get persistence mounts

### ISSUE THREAD

**Issue by samip5** [angelnu/helm-charts#141]
I need to mount eg /dev to the gluetun container, but the template doesn't allow for that.

**Comment by psych0d0g** [comment]
adding ressources definition possibilities to the template would fix that with a device-plugin as documented here: https://www.talos.dev/v1.8/kubernetes-guides/configuration/device-plugins/

but due to the chart not exposing resources in values we can not add the device to the container and pod-gateway does not work in recent runc implementations

**Comment by TheAceMan** [comment]
I was able to mount a configMap to the gluten container, assume you could mount persistent storage this way as well. This appears to mount the volume to both the pod-gateway and gluetun containers. The important parts are to create the persistence and add an additionalVolumeMounts to the gluetun specs. Below is the relevant parts of my config, I am mounting additional iptables rules I needed to get it working.

```
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gateway
spec:
  interval: 30m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system

  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.13.0

    addons:
      vpn:
        enabled: true
        type: gluetun
        gluetun:
          image:
            repository: ghcr.io/qdm12/gluetun
            tag: v3.40.0@sha256:2b42bfa046757145a5155acece417b65b4443c8033fb88661a8e9dcf7fda5a00

        additionalVolumeMounts:
          - mountPath: /iptables/post-rules.txt
            name: iptables
            readOnly: true
            subPath: post-rules.txt

    webhook:
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.12.0

    persistence:
      iptables:
        enabled: true
        type: configMap
        name: pod-gateway-post-rules
        subPath: post-rules.txt
        mountPath: "/iptables/post-rules.txt"
        readOnly: true
```
