### ISSUE TITLE
[Pod-Gateway] Init container of routed pod will not start

### ISSUE THREAD

**Issue by graytonio** [angelnu/helm-charts#86]
I tried to deploy the pod-gateway and got it all configured however when I try to deploy the terminal pod to test it it's stuck in trying to schedule the init container with the error.
```
MountVolume.SetUp failed for volume "gateway-configmap" : configmap "pod-gateway" not found
```
Since this cm is not in the same namespace this makes sense but I can't figure out what I've done wrong. The chat is deployed in a ns named pod-gateway and the terminal is in a ns called pirate-ship.

Helm Values
```
image:
  repository: ghcr.io/angelnu/pod-gateway
  tag: v1.8.1
webhook:
  image:
    repository: ghcr.io/angelnu/gateway-admision-controller
    tag: v3.9.0
routedNamespaces:
- pirate-ship
addons:
  vpn:
    enabled: true
    type: gluetun
    gluetun:
      image: 
        repository: qmcgaw/gluetun
        tag: v3.35
    env:
      - name: VPN_SERVICE_PROVIDER
        value: private internet access
      - name: OPENVPN_USER
        valueFrom:
          secretKeyRef:
            name: openvpn-credentials
            key: openvpn-user
      - name: OPENVPN_PASSWORD
        valueFrom: 
          secretKeyRef:
            name: openvpn-credentials
            key: openvpn-password
      - name: SERVER_REGIONS
        value: US Atlanta
      - name: VPN_INTERFACE
        value: tun0
    networkPolicy:
      enabled: ture
      egress:
        - to:
          - ipBlock:
              cidr: 0.0.0.0/0
          ports:
          - port: 443
            protocol: UDP
        - to:
          - ipBlock:
              cidr: 10.0.0.0/8
settings:
  VPN_INTERFACE: tun0
  VPN_BLOCK_OTHER_TRAFFIC: true
  VPN_TRAFFIC_PORT: 443
  NOT_ROUTED_TO_GATEWAY_CIDRS: "10.0.0.0/8"

```
